workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    triggering:
      events: []
    environment:
      java: 17
      node: 20
      groups:
        - PROD
    scripts:
      - name: Decode keystore
        script: |
          echo "$CM_KEYSTORE" | base64 --decode > android/app/release.keystore
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: 1:781224438706:android:8f05cdecafb314e23352ab
          groups:
            - testers
          artifact_type: apk
