/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./pages/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./entities/**/*.{js,jsx,ts,tsx}",
    "./widgets/**/*.{js,jsx,ts,tsx}",
    "./features/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "grey-light": "#F2F2F2",
        "grey-medium": "#E2E2E2",
        "text-black": "#17171B",
        "text-grey": "#747476",
        "text-number": "rgba(23, 23, 27, 0.6)",
        "ui-bg-details": "#333333",
        primary: "#EA5D60",
        "on-primary": "#FFFFFF",
        "primary-container": "#EADDFF",
        "on-primary-container": "#21005D",
        secondary: "#625B71",
        "on-secondary": "#FFFFFF",
        "secondary-container": "#E8DEF8",
        "on-secondary-container": "#1D192B",
        tertiary: "#7D5260",
        "on-tertiary": "#FFFFFF",
        "tertiary-container": "#FFD8E4",
        "on-tertiary-container": "#31111D",
        error: "#B3261E",
        "on-error": "#FFFFFF",
        "error-container": "#F9DEDC",
        "on-error-container": "#410E0B",
        outline: "#79747E",
        surface: "#FFFBFE",
        "on-surface": "#1C1B1F",
        "surface-container-highest": "#E7E0EC",
        "on-surface-variant": "#49454F",
        "inverse-surface": "#313033",
        "on-inverse-surface": "#F4EFF4",
        "inverse-primary": "#D0BCFF",
        shadow: "#000000",
        "surface-tint": "#6750A4",
        "outline-variant": "#CAC4D0",
        scrim: "#000000",
      },
    },
  },
  plugins: [],
};
